name: Build and Release
on:
  push:
    branches:
      - wael

permissions:
  contents: write
  packages: write

jobs:
  build-and-release:
    runs-on: macos-12 #mac-mini-ios-sh-1
    steps:
    - name: Checkout ${{ github.ref_name }}
      uses: actions/checkout@v4
    - name: CocoaPod Install
      run: pod install
    - name: Lint code using SwiftLint
      run: swiftlint lint --reporter github-actions-logging
      
